module TimeOff.Server.Program

open Shared.Types
open ProtoPersist

open Suave

[<EntryPoint>]
let main _ =

  let jwtEncoder = JsonWebTokenEncoder PassPhrase.AutoGenerated 
  let authentifier = Authentifier(TokenExtractor(), jwtEncoder)

  let employeeRepository =
    FileSystem.DirectoryRepository.Create<string, Employee>(@"..\..\DB\employees", id)
    |> Agent.AgentRepository.Wrap

  let config =
    { defaultConfig with
       bindings = [ HttpBinding.create HTTP System.Net.IPAddress.Loopback 8081us ] }

  Server.mainWebPart authentifier employeeRepository
  |> startWebServer config

  0