module TimeOff.Server.Server

open Shared.Types

open Suave
open Suave.Operators
open Suave.Filters
open Suave.RequestErrors
open Suave.Successful
open Suave.Writers

open ProtoPersist

let mainWebPart (authentifier: Authentifier) (userRepository: IRepository<string, User>) =
  choose [

    // Login
    POST >=> path Shared.ServerUrls.Login >=> authentifier.LoginWebPart

    // All other endpoints require authentication
    authentifier.Authenticate
      >=> choose [

        // Users management
        pathStarts Shared.ServerUrls.Users
          >=> Authorization.whenUserHasRole HumanResources
          >=> RestFul.rest Shared.ServerUrls.Users (scanSingleStringFormat (Shared.ServerUrls.Users + "%s")) userRepository

        // Vacation management
        GET >=> pathScan (scanSingleStringFormat (Shared.ServerUrls.UserVacation + "%s")) UserVacation.balanceForUser
      ]

    NOT_FOUND "Page not found."
  ]

let config =
  { defaultConfig with
     bindings = [ HttpBinding.create HTTP System.Net.IPAddress.Loopback 8081us ] }

[<EntryPoint>]
let main _ =

  let jwtEncoder = JsonWebTokenEncoder PassPhrase.AutoGenerated 
  let authentifier = Authentifier jwtEncoder

  let userRepository =
    FileSystem.DirectoryRepository.Create<string, User>(@"..\..\DB\users", id)
    |> Agent.AgentRepository.Wrap

  mainWebPart authentifier userRepository
  |> startWebServer config

  0